### ISSUE TITLE
Morphological features are lost in russian model

### ISSUE THREAD

**Issue by SergeyShk** [explosion/spacy-stanza#28]
spaCy version: 2.1.9
spaCy-stanza version: 0.2.1

```python
import stanza
from spacy_stanza import StanzaLanguage

stanza.download('ru')
snlp = stanza.Pipeline(lang="ru")
nlp = StanzaLanguage(snlp)
text = "Мама мыла раму"
```

Using stanza, i get this:
```python
for sentence in snlp(text).senteces:
	for word in sentence.words:
		print(word.feats)

# Animacy=Anim|Case=Nom|Gender=Fem|Number=Sing
# Animacy=Inan|Case=Gen|Gender=Neut|Number=Sing
# Animacy=Inan|Case=Acc|Gender=Fem|Number=Sing
```

Using spac-stanza, i get this:
```python
for token in nlp(text):
	print(token.tag_)

# 
# 
# 
```
But other annotations (such as lemma, pos, dep etc.) are available.

**Comment by ines** [comment]
Thanks for the report! It looks like the wrapper currently only uses the `token.xpos` for the tag, which seems to not exist here. (Or maybe it changed in Stanza update and I missed it.) Adding (or appending?) the `token.feats` here should fix it:

https://github.com/explosion/spacy-stanza/blob/58f562726aaf1c5f7e72e5313e7aece46bd33d7d/spacy_stanza/language.py#L157

**Comment by SergeyShk** [comment]
Yes, xpos does not exist in the Russian models. Can you fix this in the new version?

**Comment by fingoldo** [comment]
Any update on this? stanza still seems to be missing xpos for Russian.

**Comment by adrianeboyd** [comment]
Just going through older issues...

The default `ru` models don't contain xpos, so for now `spacy-stanza` uses upos for `token.tag` if there's no xpos available. I think some of the non-default Russian models do contain xpos (I think Russian GSD looks like it does?).

Please feel free to reopen if you're still running into issues!
