### ISSUE TITLE
Specify GPU to use

### ISSUE THREAD

**Issue by AlexeySlvv** [explosion/spacy-stanza#45]
I have a system with two GPUs and create pipes with this code

`pipe = stanza.Pipeline(lang=lang, use_gpu=True)`

Is there any way to specify what GPU should pipes use? Maybe option like device="cuda:0"?

**Comment by adrianeboyd** [comment]
Hi, this is more of a `stanza` question than a `spacy-stanza` question. But I think you typically manage this through `torch`. It looks like you can probably control it with `CUDA_VISIBLE_DEVICES` or by importing `torch` and using its methods to select the device.

**Comment by AlexeySlvv** [comment]
Thanks. Moreover, this question has been already asked and solved.

https://github.com/stanfordnlp/stanza/issues/164
