### ISSUE TITLE
Update stanza in requirements to fix this urgent bug

### ISSUE THREAD

**Issue by chaouiy** [explosion/spacy-stanza#47]
Stanza released new version to fix this urgent bug : https://github.com/stanfordnlp/stanza/issues/417

please update requirements.txt in spacy-stanza to get the fix

**Comment by giorgosera** [comment]
Yes, please! I stumbled upon the same issue and need the version bump.

Thanks

**Comment by giorgosera** [comment]
hey @adrianeboyd :)

I wanted to check what's the status of the PR that closes this issue. Do you have a rough estimate on when it'll be merged and released?

Thanks
