### ISSUE TITLE
User Warnings make parsing Late

### ISSUE THREAD

**Issue by chaouiy** [explosion/spacy-stanza#52]
I am parsing a big corpus that takes days to index. It is an arabic corpus so I need `spacy-stanza.`
I have noticed that it is printing for each sentence I parse `UserWarning: Can't set named entities because of multi-word token expansion or because the character offsets don't map to valid tokens produced by the Stanza tokenizer`
This makes the parsing a lot slower. I suggest to remove these warnings

**Comment by adrianeboyd** [comment]
Hi, you can use python `warnings` filters to manage how these warnings are handled: https://docs.python.org/3/library/warnings.html#the-warnings-filter

**Comment by isaac47** [comment]
Hi,
I still have the same ussue. How to simply shut up all UserWarning?

**Comment by polm** [comment]
You can call code with `python -W ignore script.py` to turn off all warnings ([docs](https://docs.python.org/3/using/cmdline.html#cmdoption-w)). This is not special or unique to spaCy.

**Comment by adrianeboyd** [comment]
Just going through some older issues...

It sounds like this was resolved, but please feel free to reopen if you're still running into issues!
