### ISSUE TITLE
Entry points for additional languages are required

### ISSUE THREAD

**Issue by jcastanohiba** [explosion/spacy-stanza#56]
So far the only language specified in the entry points is English, if another language is required the entry points have to be manually modified.  This is not nice. I suggest that the entry points, should have the languages available for stanza.

Relevant part of the code of setup.py, is line 37:

It states:

entry_points={"spacy_languages": ["stanza_en = spacy_stanza:StanzaLanguage"], the list should be like:

entry_points={"spacy_languages": ["stanza_en = spacy_stanza:StanzaLanguage", "stanza_es = spacy_stanza:StanzaLanguage", "stanza_pt"= spacy_stanza:StanzaLanguage",...]

**Comment by adrianeboyd** [comment]
Hi, this will be fixed in v0.2.5.
