### ISSUE TITLE
Question: fine tuning stanza models from within Spacy

### ISSUE THREAD

**Issue by srsridharan** [explosion/spacy-stanza#74]
## Details
After importing a Stanza model into Spacy (e.g. the bio NER model in stanza - which also contains its own word embedding), could I use spacy/thinc to train or finetune the Stanza model (which itself is a pytorch model under the hood). 

As training/finetuning  NER in Stanza is currently quite cumbersome (and doing  NER tuning in Spacy is amazingly easy) that would be a huge plus! Any insights are welcome. I'm not too optimistic simply because Stanza NER training itself is far from smooth at present - with a range of parameters that need to be set. However I would be happy to be contradicted by the Spacy team given their familiarity with this.

**Comment by adrianeboyd** [comment]
In `spacy-stanza`, the stanza model is run as part of the tokenization (what happens in `nlp.make_doc`), so it's not loaded in the same way as the built-in trainable components.

I would imagine that it's technically possible some effort in `thinc` and `spacy`, but I think you're probably better off using their training methods.
