### ISSUE TITLE
stanza.download('en') not working

### ISSUE THREAD

**Issue by ghltshubh** [explosion/spacy-stanza#75]
I am getting the following error: `TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

I am using `python 3.7` and `stanza 3.0.0`

**Comment by adrianeboyd** [comment]
Sorry, I'm not sure what's going on from this report. You're reporting an error related to `stanza` in the `spacy-stanza` repo, and while there is a spacy v3.0.0, there's no stanza v3.0.0.

Can you provide the the versions of `spacy`, `spacy-stanza`, and `stanza` (or the whole output of `pip freeze`) and more details about the exact code you're running?
