### ISSUE TITLE
AttributeError: module 'spacy_stanza' has no attribute 'load_pipeline'

### ISSUE THREAD

**Issue by ghshin-github** [explosion/spacy-stanza#83]
Hello all,

Do you have any idea about this error message? I installed spacy-stanza through pip3 and worked on it in Jupyter Notebook.

Best,
Gyu-Ho

**Comment by adrianeboyd** [comment]
`load_pipeline` was added in v1.0, so double-check that you have spacy v3.x and spacy-stanza v1.x.

**Comment by ghshin-github** [comment]
Thanks for the quick response. I will make sure the versions and try to figure it out.
